# Development Stage
FROM node:20-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN  apt-get update &&  apt-get -y install procps && apt-get install -y openssl
WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

COPY . .


RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm prisma generate


